// swift-tools-version: 6.0
import PackageDescription

let package = Package(
    name: "EAVTests",
    platforms: [.macOS(.v14)],
    targets: [
        .target(
            name: "EAVCore",
            path: ".",
            exclude: [
                "build",
                "EmacsAgendaViewer.xcodeproj",
                "Tests",
                "EmacsAgendaViewer/App.swift",
                "EmacsAgendaViewer/Assets.xcassets",
                "EmacsAgendaViewer/Info.plist",
                "EmacsAgendaViewer/Views/AllTasksView.swift",
                "EmacsAgendaViewer/Views/ContentStates.swift",
                "EmacsAgendaViewer/Views/RootView.swift",
                "EmacsAgendaViewer/Views/SettingsView.swift",
                "EmacsAgendaViewer/Views/TodayView.swift",
                "EmacsAgendaViewer/Views/UpcomingView.swift",
                "EmacsAgendaViewer/Views/Components/DateBadge.swift",
                "EmacsAgendaViewer/Views/Components/PriorityBadge.swift",
                "EmacsAgendaViewer/Views/Components/TagChips.swift",
                "EmacsAgendaViewer/Views/Components/TaskRow.swift",
                "EmacsAgendaViewer/Views/Components/TodoStatePill.swift",
                "project.yml",
                "EmacsAgendaViewerMac/App.swift",
                "EmacsAgendaViewerMac/CalendarDropZone.swift",
                "EmacsAgendaViewerMac/CalendarGridItem.swift",
                "EmacsAgendaViewerMac/CalendarState.swift",
                "EmacsAgendaViewerMac/CalendarSync.swift",
                "EmacsAgendaViewerMac/CaptureSheet.swift",
                "EmacsAgendaViewerMac/CreateEventSheet.swift",
                "EmacsAgendaViewerMac/EventKitService.swift",
                "EmacsAgendaViewerMac/GroupSection.swift",
                "EmacsAgendaViewerMac/Info.plist",
                "EmacsAgendaViewerMac/MacAllTasksView.swift",
                "EmacsAgendaViewerMac/CalendarDayGrid.swift",
                "EmacsAgendaViewerMac/CalendarItemViews.swift",
                "EmacsAgendaViewerMac/CalendarOverlap.swift",
                "EmacsAgendaViewerMac/MacCalendarView.swift",
                "EmacsAgendaViewerMac/MacEisenhowerView.swift",
                "EmacsAgendaViewerMac/MacHabitsView.swift",
                "EmacsAgendaViewerMac/MacInboxView.swift",
                "EmacsAgendaViewerMac/MacLogbookView.swift",
                "EmacsAgendaViewerMac/MacClockDock.swift",
                "EmacsAgendaViewerMac/MacEventBanners.swift",
                "EmacsAgendaViewerMac/MacRowActionsBuilder.swift",
                "EmacsAgendaViewerMac/MacScheduleTray.swift",
                "EmacsAgendaViewerMac/MacTaskRow.swift",
                "EmacsAgendaViewerMac/MacTodayView.swift",
                "EmacsAgendaViewerMac/MacToolbar.swift",
                "EmacsAgendaViewerMac/MacUpcomingView.swift",
                "EmacsAgendaViewerMac/RefileSheet.swift",
                "EmacsAgendaViewerMac/RootView.swift",
                "EmacsAgendaViewerMac/SettingsView.swift",
                "EmacsAgendaViewerMac/TaskExpandedCard.swift",
            ],
            sources: [
                "EmacsAgendaViewer/Models/AgendaEntryClassification.swift",
                "EmacsAgendaViewer/Models/Checklist.swift",
                "EmacsAgendaViewer/Models/Models.swift",
                "EmacsAgendaViewer/Networking/APIClient.swift",
                "EmacsAgendaViewer/Networking/DaemonHostPidParse.swift",
                "EmacsAgendaViewer/Networking/EventSubscriber.swift",
                "EmacsAgendaViewer/State/AppSettings.swift",
                "EmacsAgendaViewer/State/CalendarLaneAssign.swift",
                "EmacsAgendaViewer/State/CalendarWeekMath.swift",
                "EmacsAgendaViewer/State/ClockManager.swift",
                "EmacsAgendaViewer/State/Debouncer.swift",
                "EmacsAgendaViewer/State/HabitStats.swift",
                "EmacsAgendaViewer/State/CalendarStableId.swift",
                "EmacsAgendaViewer/State/CaptureTemplateExpander.swift",
                "EmacsAgendaViewer/State/CaptureTemplateParser.swift",
                "EmacsAgendaViewer/State/NotesRenderer.swift",
                "EmacsAgendaViewer/State/OrgInlineCore.swift",
                "EmacsAgendaViewer/State/Sorting.swift",
                "EmacsAgendaViewer/State/TaskFilters.swift",
                "EmacsAgendaViewer/State/OptimisticPatch.swift",
                "EmacsAgendaViewer/State/TasksStore.swift",
                "EmacsAgendaViewer/State/TodayClassifier.swift",
                "EmacsAgendaViewer/Theme.swift",
                "EmacsAgendaViewer/Views/Components/TaskDisplayable.swift",
                "EmacsAgendaViewer/Color+Hex.swift",
                "EmacsAgendaViewerMac/MacNotesRenderer.swift",
                "EmacsAgendaViewerMac/CalendarAccess.swift",
            ]
        ),
        .testTarget(
            name: "EAVTests",
            dependencies: ["EAVCore"],
            path: "Tests/EAVTests",
            resources: [.copy("Fixtures")]
        ),
    ]
)
